### ISSUE TITLE
Attempting to build solidrun-imx6

### ISSUE THREAD

**Issue by jaredwolff** [resin-os/resin-fsl-arm#56]
Hey guys,

I'm trying to build the solidrun-imx6 and having some serious issues trying to re-produce a working environment to get the build going. I'm stuck at the phase where the scripts are checking for a working Docker instance.

**Expected behavior**
Complete my build using the following command:

```
./resin-yocto-scripts/build/barys -r --shared-downloads $(pwd)/shared-downloads/ --shared-sstate $(pwd)/shared-sstate/ -m solidrun-imx6
```

**Actual behavior**

```
Nitrogen 6X                              : $ MACHINE=nitrogen6x bitbake resin-image
Hummingboard                             : $ MACHINE=solidrun-imx6 bitbake resin-image

[000000001][LOG]Resin build initialized in build.
[000000001][LOG]Run build for solidrun-imx6: MACHINE=solidrun-imx6 bitbake resin-image 
[000000001][LOG]This might take a while ...
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
ERROR: /home/vagrant/resin-fsl-arm/build/../layers/meta-resin/meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb: docker-disk: Docker needs to run on your host and current user must be able to use it.4
ERROR: Failed to parse recipe: /home/vagrant/resin-fsl-arm/build/../layers/meta-resin/meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
ERROR: /home/vagrant/resin-fsl-arm/build/../layers/meta-resin/meta-resin-common/recipes-containers/docker-disk/docker-custom-disk.bb: docker-disk: Docker needs to run on your host and current user must be able to use it.
```

But, when I run the following:

```
cat /var/run/docker.pid 
13998
```

and check 
```
ls proc
1    13     14004  17324  2      24  35   410  427  5    79    84         cgroups   diskstats    fs          kcore       loadavg  mtrr          slabinfo       sysvipc      vmallocinfo
10   133    144    17326  20     25  36   415  429  691  8     9          cmdline   dma          interrupts  keys        locks    net           softirqs       timer_list   vmstat
103  136    146    17327  20978  27  37   417  431  7    80    acpi       consoles  driver       iomem       key-users   meminfo  pagetypeinfo  stat           timer_stats  zoneinfo
104  13910  15     18     21     28  38   424  437  74   8148  asound     cpuinfo   execdomains  ioports     kmsg        misc     partitions    swaps          tty
11   13998  16     18405  22     29  380  425  438  75   8214  buddyinfo  crypto    fb           irq         kpagecount  modules  sched_debug   sys            uptime
12   140    17     19     23     3   401  426  455  78   83    bus        devices   filesystems  kallsyms    kpageflags  mounts   self          sysrq-trigger  version
```

It obviously shows that the docker daemon is running. 

Note my vagrantfile is the following:

```
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  # downloads and configuration dependencies
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    echo "Installing dependencies..."

    # quiets some stdin errors
    export DEBIAN_FRONTEND=noninteractive

    sudo apt-get update

    # runtime & build requirements
    sudo apt-get install git curl python\
      apt-transport-https \
      ca-certificates \
      curl \
      software-properties-common \
      g++ diffstat gawk chrpath -y

    # Get gpg file for apt-get
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -

    # Add repo
    sudo add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
      $(lsb_release -cs) \
      stable"

    # Get node source info
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

    sudo apt-get install docker-ce nodejs jq -y

    apt-get clean && rm -rf /var/lib/apt/lists/*

    # Download poky related stuff
    echo "Installing source"
    git clone --recursive https://github.com/resin-os/resin-fsl-arm.git
    cd resin-fsl-arm

    echo "Ready"
  SHELL

end
```

**Comment by jaredwolff** [comment]
I've also tried running this in a Docker using the CROPs image but with no luck as well (same error)

**Comment by floion** [comment]
Hi,
then it must be this other part which is failing:

    # Test docker execute permission
    cmd = "docker images > /dev/null 2>&1"
    child = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    cmd_output = child.communicate()[0]
    if child.returncode != 0:
        return "no"

Can you test that too?

**Comment by floion** [comment]
I think your user needs to be added to the docker group

**Comment by jaredwolff** [comment]
@floion adding the user to the docker group did the trick. It wouldn't be a bad idea to note that `barys` should be run as root or to make sure the current user is associated with the _docker_ group

**Comment by agherzan** [comment]
Running barys is a bad idea because it runs the yocto build system (bitbake) which you wonldn't want to run as root. I'm pretty sure that running barys as root would make the build system bail out with an explicit error.

**Comment by floion** [comment]
@agherzan actually the yocto build system should be more explicit about what exactly failed, and suggest fixes. Running as root indeed is something we should not consider

**Comment by agherzan** [comment]
I'm pretty sure the error is pretty explicit? Did you try to reproduce?

**Comment by floion** [comment]
No @agherzan , there was no need to try and reproduce as the user posted the error in his first post.

> ERROR: /home/vagrant/resin-fsl-arm/build/../layers/meta-resin/meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb: docker-disk: Docker needs to run on your host and current user must be able to use it.4
ERROR: Failed to parse recipe: /home/vagrant/resin-fsl-arm/build/../layers/meta-resin/meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb
ERROR: /home/vagrant/resin-fsl-arm/build/../layers/meta-resin/meta-resin-common/recipes-containers/docker-disk/docker-custom-disk.bb: docker-disk: Docker needs to run on your host and current user must be able to use it.

And as I said earlier, "actually the yocto build system should be more explicit about what exactly failed, and suggest fixes", we should change the error message to reflect the fact that the user may not be added to the docker group. That is what I meant

**Comment by agherzan** [comment]
`Docker needs to run on your host and current user must be able to use it.` sounds pretty explicit to me but open to suggestions and PR.

**Comment by willoftw** [comment]
For anyone in the future happening upon this issue. I had the same problem until I actually started running some docker commands eg 'docker image list'. Must do some additional initialisation behind the scenes.

**Comment by rush0825** [comment]
I have same problem and I am sure that my account have docker group.
I found I restart docker service can solve this issue. For your reference.

**Comment by minusplusminus** [comment]
check your `/var/run/docker.sock` rights
